### ISSUE TITLE
The current docker build has a "cannot open shared object file" error

### ISSUE THREAD

**Issue by DeflateAwning** [openscad/docker-openscad#17]
### Steps to reproduce:
1. Run `docker run --entrypoint=/bin/bash -it openscad/openscad:latest` ([link to version](https://hub.docker.com/layers/openscad/openscad/latest/images/sha256-4ddd50a525e89d472d64a73d058fc0842ba886aca64eee85b78a12ad35fe49d7?context=explore))
2. Run `openscad --version`
3. See the error message:
```
openscad: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

### Steps to fix:
In the container, I ran these commands:
```bash
apt install binutils
strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

After that, running `openscad --version` was successful. The fix came from [this unrelated thread](https://github.com/YosysHQ/nextpnr/issues/375#issuecomment-570002328).

**Comment by t-paul** [comment]
Fixed via https://github.com/openscad/docker-openscad/pull/18. Thanks!

**Comment by DeflateAwning** [comment]
The current latest tag has this error still:

```
docker run \
>     -it \
>     --rm \
>     -v $(pwd):/openscad \
>     -u $(id -u ${USER}):$(id -g ${USER}) \
>     openscad/openscad:latest \
>     openscad -o buckle.stl buckle.scad 
openscad: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

I think you may need to rebuild the "latest" tag using this fix. Not sure how bad that is.
